### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by bradanlane** [munnellg/EnigmaMachine#1]
Is your project open source and if so, what license do you apply to it? If you do not have a preference, then the MIT license is a good option.

**Comment by munnellg** [comment]
Hi Bradán,

Yes, the project is open source. I've added the MIT license to clarify this.

If you're planning on using this in a project of your own bear in mind that it has had very little testing. It's a quick little hack I threw together to pass the time on a rainy weekend. I'm happy to fix bugs in this repo if you find them.

**Comment by bradanlane** [comment]
Thanks for adding the LICENSE. 

I've done some elemental testing and thus far it is good. I will plan to run it against the NSA simulator.

One thing I will add is a function to rest the machine "for the next message". I have not yet determined how best to do it as I am adding this to an embedded design and need to keep code and data size front and center. You will see occasional tweets from me on the project.

**Comment by munnellg** [comment]
Assuming you're holding on to the IO stuff in enigma.c you can just reload settings.conf to reset.

If not, a buffer of 4 ints (chars if you want to push it) is all you need to store the rotation settings which should get you back to the initial state. Call `enigma_set_rotation` for each buffer element to reset.

Good luck with the project! Obviously, MIT is extremely permissive, but I'd appreciate a credit where my work is used. It helps my portfolio.

**Comment by bradanlane** [comment]
It will be awhile before I have anyone "finished" but I will include a link to your repository in any write ups of the finished system. The enigma machine is primarily a "working" plot element in a story I'm working on.

**Comment by munnellg** [comment]
Awesome! It'd be good to see this repo get some use :)
